[package]
name = "gmgmaming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
raw-window-handle = "0.6"
vulkano = "0.34"
vulkano-shaders = "0.34"
